/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Cria uma barra lateral apenas com o que está na pasta "documentacao"
  documentacaoSidebar: [{type: 'autogenerated', dirName: 'documentacao'}],
  
  // Cria uma barra lateral apenas com o que está na pasta "tutorial"
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
  
  // Cria uma barra lateral apenas com o que está na pasta "informacoes"
  informacoesSidebar: [{type: 'autogenerated', dirName: 'informacoes'}],
};

export default sidebars;