/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  documentacaoSidebar: [{type: 'autogenerated', dirName: 'documentacao'}],
  
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
  
  informacoesSidebar: [{type: 'autogenerated', dirName: 'Informacoes'}], 
};

export default sidebars;