/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Cria uma barra lateral apenas com o que está na pasta "documentacao"
  documentacaoSidebar: [{type: 'autogenerated', dirName: 'documentacao'}],
  
  // Cria uma barra lateral apenas com o que está na pasta "Ajuda"
  tutorialSidebar: [{type: 'autogenerated', dirName: 'Ajuda'}],
  
  // Cria uma barra lateral apenas com o que está na pasta "Informacoes"
  informacoesSidebar: [{type: 'autogenerated', dirName: 'Informacoes'}],
};

export default sidebars;